* 计算广告
** 在线广告
   广告的根本目的是广告主通过媒体达到低成本的用户接触。

   投入产出比 return on investment ROI

   大数据（big data）这一方法论在实践中唯一形成规模化营收的落地行业就是在线广告
*** 参与者
    出资人:广告主 advertiser,或者代理商 agency
    媒体:游戏,视频
    受众 audience
*** 广告类型
    品牌广告,brand awareness
    效果广告,direct response

    横幅广告 banner
    文字链广告 textual
    富媒体广告 rich media
    视频广告 video,前插,暂停
    社交广告 social,这种方式力求在用户自然关注的交互过程中尽可能自然地插入广告，也被归于原生广告的范畴中。
    移动广告 mobile
    邮件广告

*** 广告发展
    在在线广告发展的历史上，定向技术和交易形式的进化 是一条主线。

    合约广告,即采用合同约定的方式确定某一广告位在某一时间段为某特定广告主所独占，并且根据双方的要求，确定广告创意和投放策略。

    定向广告,媒体向广告主保证某个投放量， 并在此基础上确定合同的总金额以及投放量未完成情况下的赔偿方案。遵循按千次展示付费（Cost per Mille，CPM）的计费方式。

    竞价广告,供给方只向广告主保证质即单位流量的成本，但不再以合约的方式给出量的保证，换言之，对每一次展示都基本按照收益最高的原则来决策。

    上下文广告

    广告网络 ad Network,ADN,批量地运营媒体 的广告位资源，按照人群或上下文标签售卖给需求方，并用竞价的方式 决定流量分配。

    实时竞价,real time bidding,RTB,将拍卖的过程由广告主 预先出价，变成每次展示时实时出价。

    面向多个 ADN 或 媒体按人群一站式采买广告并优化投入产出比的需求方产品，我们称为 交易终端（Trading Desk，TD）。

    广告交易平台（ad Exchange，ADX）:
    需求方平台（Demand Side Platform，DSP）,基于 DSP 的广告采买非常类似于股票市场上的程序交易，我们把这 样的广告采买方式也叫作程序化交易（programmatic trade）。除了 RTB 以 外，还有其他几种程序购买的交易方式，如优选（preferred deals）以及 私有交易市场（Private Market Place，PMP）等。

将内 容与广告以某种方式统一决策或排序的广告产品——原生广告（Native AD）在近年来得到了工业界越来越多的关注。

** 计算广告基础

千 次展示期望收入（expected Cost Per Mille，eCPM）正是计算广告中最为 核心的量化指标之一

*** 广告的阶段

- 曝光,位置为王
- 关注,原则:尽量不要打断用户的任务,当用户明 确辨识出某个固定不变的广告位，并且不再认为它与自己当浏览网页的任务有关联时，他会下意识地屏蔽其中的内容。
- 理解,广告内容要在用户能理解的具体兴趣范围内，这说明了真正精准的受众定向有多么必要。
- 接受,在定向广告越来越普遍的今天，如何让合适的广告出现在合适的媒体上，即广告安全（ad safety）的问题
- 保持,充满艺术性或浪漫气质的电视汽车广告
- 决策

*** 计算广告的核心问题
